import './globals.css'

export const metadata = {
  title: 'Sismos Chile',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-neutral-900">{children}</body>
    </html>
  )
}
